select * from TRXN_KPIDD
where KPI_NIK=694

SELECT STAFF_NAMA, STAFF_SUBJABATAN FROM DATA_STAFF WHERE STAFF_NIK=694


SELECT [KPIN_TIPE], [KPIN_JUDUL], [KPIN_DESC], [KPIN_NILAI10], [KPIN_NILAI9], [KPIN_NILAI8], [KPIN_NILAI7], 
[KPIN_NILAI6], [KPIN_GROUP] FROM [DATA_KPIN] WHERE [KPIN_TIPE]='HD1' order by [KPIN_TIPE] asc


SELECT        
	S.STAFF_NIK, S.STAFF_NAMA, S.STAFF_STATUSKERJADEPT, D.KPI_KODEITEMM AS ITEM_PENILAIAN, 'Penilaian Proses ' +
    (SELECT KPIN_JUDUL FROM dbo.DATA_KPIN WHERE (KPIN_TIPE = D.KPI_KODEITEMM)) AS DESKRIPSI_ITEM_PENILAIAN, D.KPI_KODEITEM AS ITEM_DETAIL_PENILAIAN,
    (SELECT KPIN_DESC  FROM dbo.DATA_KPIN WHERE (KPIN_TIPE = D.KPI_KODEITEM)) AS DESKRIPSI_ITEM_DETAIL, D.KPI_KOMENTAR AS KOMENTAR_ATASAN, D.KPI_KOMENTAR2 AS KOEMNTAR_ATASAN2,
	-- NEW LOGIC
	CASE 
	 WHEN  D.KPI_KODEITEM = 'HD1' AND CAST(D.KPI_KOMENTAR  AS varchar(10))=100 THEN (SELECT [KPIN_NILAI10] FROM DATA_KPIN WHERE KPIN_TIPE = 'HD1')
	 WHEN  D.KPI_KODEITEM = 'HD1' AND CAST(D.KPI_KOMENTAR  AS varchar(10))=90 THEN (SELECT [KPIN_NILAI9] FROM DATA_KPIN WHERE KPIN_TIPE = 'HD1')
	 WHEN  D.KPI_KODEITEM = 'HD1' AND CAST(D.KPI_KOMENTAR  AS varchar(10))=80 THEN (SELECT [KPIN_NILAI8] FROM DATA_KPIN WHERE KPIN_TIPE = 'HD1')
	 WHEN  D.KPI_KODEITEM = 'HD1' AND CAST(D.KPI_KOMENTAR  AS varchar(10))=70 THEN (SELECT [KPIN_NILAI7] FROM DATA_KPIN WHERE KPIN_TIPE = 'HD1')
	 WHEN  D.KPI_KODEITEM = 'HD1' AND CAST(D.KPI_KOMENTAR  AS varchar(10))=60 THEN (SELECT [KPIN_NILAI6] FROM DATA_KPIN WHERE KPIN_TIPE = 'HD1')
	ELSE NULL
	END AS KOMENTAR_BY_NILAI,
	-- NEW LOGIC
	D.KPI_TAHUN AS TAHUN
FROM dbo.DATA_STAFF AS S INNER JOIN dbo.TRXN_KPIDD AS D ON S.STAFF_NIK = D.KPI_NIK

where D.KPI_KODEITEM = 'HD1' 
where s.STAFF_NIK =694


SELECT * FROM LaporanKomentarPK where STAFF_NIK = 694 and TAHUN = 2018